### PR TITLE
pprof support

### PR DESCRIPTION
**Pull request by n3integration**
Support for pprof

### CODE REVIEW

**Comment by tboerger** [comment]
This repository is just for backward compatibility, if we want a middleware for that it should be placed in a standalone repository at the gin-contrib org

**Comment by n3integration** [comment]
@tboerger - Ok. I didn't realize that this repo was not being maintained. Would you like me to close this pr and add this to the `gin-contrib` org instead? FWIW- I also have another contrib repo in the works.

**Comment by tboerger** [comment]
Doing it within gin-contrib makes more sense.

**Comment by appleboy** [comment]
@n3integration @tboerger I will create `gin-pprof` repo for @n3integration

**Comment by tboerger** [comment]
gin-contrib/pprof ;)

**Comment by appleboy** [comment]
@n3integration Please move your changes to https://github.com/gin-contrib/pprof repo.

**Pull request closed without merging**
