### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by stnc**
fixed: pongo2 template - request

### CODE REVIEW

**Review by appleboy — CHANGES_REQUESTED** [review]
please resolve the conflict.

**Comment by dieselburner** [comment]
Please reject this and blacklist this person. More info is here: #215 and https://github.com/flosch/pongo2/issues/290.

**Comment by stnc** [comment]
I did not know that it was your work, the person I refer to received from you, I am very sorry, I added you
 
https://github.com/stnc/pongo4gin/blob/main/README.md
 
https://github.com/stnc/pongo2gin/blob/master/README.md

**Comment by stnc** [comment]
ok i deleted the project, you post it please

**Pull request closed without merging**
