### PR TITLE
Session memcache

### PR DESCRIPTION
**Pull request by s-aska**
I am already using memcached on the server, I need to take advantage of this.

### CODE REVIEW

**Comment by robvdl** [comment]
That is cool, now we just need an example using BoltDB as well :)

**Comment by s-aska** [comment]
I've noticed is in now.
This project is no longer being maintenance? :/

**Comment by javierprovecho** [comment]
@s-aska we are somehow busy with university, we try to maintain this and the main repo on a best-effort basis while keeping it stable (not accepting new organization members*). I first need to fix TravisCI and then re-trigger a build to check your pull/merge request.

(*): this is because Gin is used by many people and we must keep it secure and trustworthy.

**Comment by appleboy** [comment]
move to https://github.com/gin-contrib/sessions/pull/16

**Pull request closed without merging**
