### PR TITLE
Size limiter middleware

### PR DESCRIPTION
**Pull request by tebeka**
Add a middleware to limit size of POST requests.

### CODE REVIEW

**Comment by appleboy** [comment]
@tebeka I will create new repo and move this PR to new repo on https://github.com/gin-contrib/size.

**Comment by tebeka** [comment]
Thanks

**Comment by tebeka** [comment]
@appleboy I don't see the new repo, the URL above redirect to the `expvar` package.

**Comment by appleboy** [comment]
@tebeka Sorry.

**Comment by tebeka** [comment]
No worries :)

**Comment by appleboy** [comment]
@tebeka Move to https://github.com/gin-contrib/size but testing fail.

**Pull request closed without merging**
