### PR TITLE
Corrupt GZIP stream when calling WriteString

### PR DESCRIPTION
**Pull request by mcastilho**
This fixes code-review requests mentioned in https://github.com/gin-gonic/contrib/pull/59

Gin-Gonic member asked if someone else could open another PR for it... Here it is...

### CODE REVIEW

**Comment by tboerger** [comment]
Now you are changing a lot more than the gzip part ;)

**Comment by mcastilho** [comment]
@tboerger I am trying to make Travis pass again

**Comment by appleboy** [comment]
@mcastilho You should only change GZIP folder. Please create another PR for another folder changes.

**Comment by mcastilho** [comment]
@appleboy @tboerger The other commits have been reverted. I will open different PR for the Travis Fix.

**Comment by appleboy** [comment]
@mcastilho Thanks.

**Pull request merged**
