### PR TITLE
Add jwt middleware

### PR DESCRIPTION
**Pull request by appleboy**
This is a middleware for Gin.

It uses jwt-go to provide a jwt authentication middleware. It provides additional handler functions to provide the login api that will generate the token and an additional refresh handler that can be used to refresh tokens.

@javierprovecho Do you want to remove jwt folder? If so, I can handle it.

closed #85 #84 #50

https://github.com/appleboy/gin-jwt

### CODE REVIEW

**Comment by appleboy** [comment]
ping @javierprovecho

**Comment by appleboy** [comment]
ping @javierprovecho

**Comment by appleboy** [comment]
ping @javierprovecho

**Comment by javierprovecho** [comment]
@appleboy sorry for delay, last two weeks were holidays and i was busy getting back to work and to university. gimme some minutes to review this, thank you!

**Comment by javierprovecho** [comment]
@appleboy merged!

**Comment by javierprovecho** [comment]
@appleboy what do you mean by removing jwt folder? isn't that middleware functional?

**Comment by appleboy** [comment]
@javierprovecho Why closed this PR? 

I implement all feature and add example on `gin-jwt` [README](https://github.com/appleboy/gin-jwt) which cover the [jwt folder example](https://github.com/gin-gonic/contrib/tree/master/jwt). So I think it can be removed by this PR.

**Comment by javierprovecho** [comment]
@appleboy sorry, not my intention. I was pretty sure I clicked merge. Sorry again.

**Comment by javierprovecho** [comment]
@appleboy let me see where does #85 pr goes. Thanks anyway for your contribution

**Pull request merged**
