### PR TITLE
adding jwt cognito middleware

### PR DESCRIPTION
**Pull request by akhettar**
Hi there, I wrote a middleware to authenticate JWT tokens issued by AWS Cognito. Please do not hesitate to contact me if you need more details.

Kind regards,

Ayache

### CODE REVIEW

**Review by dieselburner — APPROVED** [review]
Clean. The middleware is well documented and looks mature. 👍🏻

**Comment by akhettar** [comment]
Thank you @dieselburner, really appreciated

**Comment by akhettar** [comment]
@dieselburner is this ready to be merged?

**Comment by dieselburner** [comment]
> @dieselburner is this ready to be merged?

I'm not a maintainer. I just reviewed your change.

**Review by appleboy — APPROVED** [review]

**Pull request merged**
