### PR TITLE
Added support for compressed POST requests.

### PR DESCRIPTION
**Pull request by oryband**
Updated tests and example.
Added comments to satisfy golint.

Please **close and don't merge #36** , this is the updated PR.

### CODE REVIEW

**Comment by manucorporat** [comment]
may this be a different middleware?

**Comment by bolshoy** [comment]
could be, because it uses different http headers. But I think it better encapsulates gzip library this way.

**Comment by manucorporat** [comment]
@bolshoy I may want to provide gzipped responses but I don't requests.
ok, how about this? same package but different middlewares.

**Comment by manucorporat** [comment]
also, I did some changes. Please, pull the last version!

**Comment by bolshoy** [comment]
@manucorporat different middlewares ok, but there's already a "gzip" folder, so either both of them in subfolders or two separate folders for request/reply gzip support.

**Comment by oryband** [comment]
you mean request/response, not "reply"

**Comment by manucorporat** [comment]
nah, same folder. KISS, just create a new `.go` file.

**Comment by manucorporat** [comment]
also, we have should rename the package to `compression` since, gzip is just a specific case.

**Comment by manucorporat** [comment]
@mopemope

**Comment by manucorporat** [comment]
Also, we should consider to skip compression for already compressed formats.
Here a list: gif, jpeg, png, avi, mov, mp3

**Comment by bolshoy** [comment]
@manucorporat 

Here are some of the settings we need to consider (loosely based on http://httpd.apache.org/docs/2.2/mod/mod_deflate.html):

compress filters
- input 
- output

compression format support
- gzip
- deflate
- bzip2, etc

additional compression settings (output only)
- compression level
- buf-size etc
- force-gzip (response always compressed)
- mime types to compress
	default: text/html text/plain text/xml text/css text/javascript application/javascript  application/json

There should be some defaults in case no explicit settings are provided, but the full config may look like this:
```
inputOptions := map[string]string{
	"format": ["gzip", "deflate", "bzip2"],
}
outputOptions := map[string]string{
	"format": ["gzip", "deflate", "bzip2"],
	"level": 8,
	"buf-size": 8096,
	"force": false,
	"mime-types": ["text/html", "text/javascript", "application/javascript", "application/json"],
}
gin.Use(compress.InputFilter(inputOptions))
gin.Use(compress.OutputFilter(outputOptions))
```

**Comment by oryband** [comment]
@manucorporat @bolshoy updated branch for gin v1.0, switched:
```go
c.Error(err, nil) // Old
c.Error(err) // New
```

**Comment by oryband** [comment]
@manucorporat we're working on an update for this branch right now to fit v1.0 changes, please don't merge yet.
@bolshoy fyi

**Comment by bolshoy** [comment]
@manucorporat Separated input and output filters, added output options and mime type detection by URL extension.

**Comment by oryband** [comment]
:+1: yay!

please merge :)

**Comment by oryband** [comment]
@manucorporat maybe merge this? been some time

**Comment by oryband** [comment]
@manucorporat ping

**Pull request closed without merging**
