### PR TITLE
fixes broken tests

### PR DESCRIPTION
**Pull request by shawnzhu**
* uses `github.com/dgrijalva/jwt-go` v3 API
* fixes naming in `cors/cors_test.go`

### CODE REVIEW

**Comment by shawnzhu** [comment]
Fixing the last test failure

**Comment by shawnzhu** [comment]
@appleboy would you please take a look at this one?

**Comment by tboerger** [comment]
I'm OK with these changes since it just fixes the broken tests.

**Comment by appleboy** [comment]
@shawnzhu Nice work.

**Pull request merged**
