### PR TITLE
fix package name and directories

### PR DESCRIPTION
**Pull request by wataru420**
I fixed the packages about example codes. 
It made error when use some tools like [GB](https://getgb.io/).

### CODE REVIEW

**Comment by gotokatsuya** [comment]
:+1: 

I have a same problem.


@manucorporat 

Could you merge this PR ?

**Comment by gotokatsuya** [comment]
Please check https://github.com/gin-gonic/contrib/pull/70 too.

**Comment by kawaken** [comment]
+1

I hava a same problem when using with [gom](https://github.com/mattn/gom).

**Comment by shawnzhu** [comment]
I've included a fix in #124 by separating two examples into two packages.

**Comment by appleboy** [comment]
fixed by #124

**Pull request closed without merging**
